package update

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"

	"mistervision/internal/release"
	updateapi "mistervision/internal/update"
)

const maxArchive = 96 << 20

func downloadClient() *http.Client {
	return &http.Client{Timeout: 5 * time.Minute, CheckRedirect: func(req *http.Request, via []*http.Request) error {
		if len(via) >= 5 || !downloadHost(req.URL) {
			return errors.New("untrusted release redirect")
		}
		return nil
	}}
}

func downloadHost(u *url.URL) bool {
	return u.Scheme == "https" && u.User == nil && u.Port() == "" && (u.Hostname() == "github.com" || u.Hostname() == "release-assets.githubusercontent.com" || u.Hostname() == "objects.githubusercontent.com")
}

func (i *Installer) response(ctx context.Context, endpoint string) (*http.Response, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, endpoint, nil)
	if err != nil {
		return nil, err
	}
	if !downloadHost(req.URL) {
		return nil, errors.New("untrusted release URL")
	}
	req.Header.Set("User-Agent", "MiSTerVision")
	resp, err := i.client.Do(req)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode != http.StatusOK {
		resp.Body.Close()
		return nil, fmt.Errorf("release download: HTTP %d", resp.StatusCode)
	}
	return resp, nil
}

func (i *Installer) download(ctx context.Context, stage string, status release.Status, notify func(updateapi.Progress)) (path string, resultErr error) {
	defer func() {
		if resultErr != nil {
			resultErr = errors.Join(updateapi.ErrDownload, resultErr)
		}
	}()
	name := release.BundleName(status.Latest)
	base := "https://github.com/trentnix/mistervision/releases/download/" + status.Latest + "/"
	resp, err := i.response(ctx, base+"SHA256SUMS")
	if err != nil {
		return "", err
	}
	data, readErr := io.ReadAll(io.LimitReader(resp.Body, (64<<10)+1))
	resp.Body.Close()
	if readErr != nil {
		return "", readErr
	}
	sums, err := checksums(data)
	if err != nil {
		return "", errors.Join(updateapi.ErrVerification, err)
	}
	expected, ok := sums[name]
	if !ok {
		return "", errors.Join(updateapi.ErrVerification, errors.New("release archive checksum is missing"))
	}
	resp, err = i.response(ctx, base+name)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	if resp.ContentLength > maxArchive {
		return "", errors.Join(updateapi.ErrVerification, errors.New("release archive is too large"))
	}
	path = filepath.Join(stage, "archive.zip")
	file, err := os.OpenFile(path, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0600)
	if err != nil {
		return "", err
	}
	hash := sha256.New()
	progress := &downloadProgress{notify: notify, total: max(0, resp.ContentLength)}
	size, err := io.Copy(io.MultiWriter(file, hash, progress), io.LimitReader(resp.Body, maxArchive+1))
	if closeErr := file.Close(); err == nil {
		err = closeErr
	}
	if err != nil {
		return "", err
	}
	if size > maxArchive {
		return "", errors.Join(updateapi.ErrVerification, errors.New("release archive is too large"))
	}
	if hex.EncodeToString(hash.Sum(nil)) != expected {
		return "", errors.Join(updateapi.ErrVerification, errors.New("release archive checksum mismatch"))
	}
	return path, nil
}

type downloadProgress struct {
	notify          func(updateapi.Progress)
	received, total int64
	last            time.Time
}

func (p *downloadProgress) Write(data []byte) (int, error) {
	p.received += int64(len(data))
	if time.Since(p.last) >= 100*time.Millisecond {
		p.notify(updateapi.Progress{Phase: updateapi.Downloading, Received: p.received, Total: p.total})
		p.last = time.Now()
	}
	return len(data), nil
}

// checksums accepts the sha256sum format generated by release packaging. It
// rejects duplicate names instead of allowing a later line to replace a digest.
func checksums(data []byte) (map[string]string, error) {
	if len(data) > 64<<10 {
		return nil, errors.New("checksum list is too large")
	}
	result := make(map[string]string)
	for _, line := range strings.Split(strings.TrimSpace(string(data)), "\n") {
		digest, name, ok := strings.Cut(line, "  ")
		decoded, err := hex.DecodeString(digest)
		if !ok || err != nil || len(decoded) != 32 || name == "" || strings.ContainsAny(name, "\r\x00") || result[name] != "" {
			return nil, errors.New("invalid checksum list")
		}
		result[name] = strings.ToLower(digest)
	}
	return result, nil
}
